{...}: {
  boot.kernelParams = [
    "kernel.kptr_restrict=2"
    "kernel.dmesg_restrict=1"
    "kernel.printk=3 3 3 3"
    "kernel.unprivileged_bpf_disabled=1"
    "net.core.bpf_jit_harden=2"
    "dev.tty.ldisc_autoload=0"
    "vm.unprivileged_userfaultfd=0"
    "kernel.kexec_load_disabled=1"
    "kernel.sysrq=4"
    "kernel.unprivileged_userns_clone=0"
    "kernel.perf_event_paranoid=3"
    "net.ipv4.tcp_syncookies=1"
    "net.ipv4.tcp_rfc1337=1"
    "net.ipv4.conf.all.rp_filter=1"
    "net.ipv4.conf.default.rp_filter=1"
    "net.ipv6.conf.all.accept_ra=0"
    "net.ipv6.conf.default.accept_ra=0"
    "net.ipv4.tcp_sack=0"
    "net.ipv4.tcp_dsack=0"
    "net.ipv4.tcp_fack=0"
    "kernel.yama.ptrace_scope=2"
    "vm.mmap_rnd_bits=32"
    "vm.mmap_rnd_compat_bits=16"
    "fs.protected_symlinks=1"
    "fs.protected_hardlinks=1"
    "fs.protected_fifos=2"
    "fs.protected_regular=2"
    # Arguments
    "slab_nomerge"
    "init_on_alloc=1"
    "init_on_free=1"
    "page_alloc.shuffle=1"
    "pti=on"
    "randomize_kstack_offset=on"
    "vsyscall=none"
    "debugfs=off"
    "oops=panic"
    "module.sig_enforce=1"
    "lockdown=confidentiality"
    "mce=0"
    "quiet"
    "loglevel=0"
    # Vuln mit
    "spectre_v2=on"
    "spec_store_bypass_disable=on"
    "tsx=off "
    "tsx_async_abort=full,nosmt"
    "mds=full,nosmt"
    "l1tf=full,force"
    "nosmt=force "
    "kvm.nx_huge_pages=force"

    # Misc
    "ipv6.disable=1"
    "net.ipv4.tcp_timestamps=0"
  ];
}
